language: java
sudo: false
install: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
env:
  global:
    TERM=dumb
notifications:
  email: false